version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DBURL: dpg-crngjso8fa8c738g0v0g-a.oregon-postgres.render.com/librarydb_kbws
      DBNAME: librarydb_kbws
      DBUSERNAME: postgresql
      DBPASSWORD: k78f31qD3cUgkqVmGeZ6YlRltTSifAER

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: k78f31qD3cUgkqVmGeZ6YlRltTSifAER
      POSTGRES_DB: librarydb_kbws
